# DATABASE
MYSQL_USERNAME: root
MYSQL_PASSWORD: password
MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DATABASE: youtube

#SERVER
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

# EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <your email>
EMAIL_PASSWORD: <your password>
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

UI_APP_URL: http://localhost:4200
