version: '1.0'

services:
  youtubeclone:
    container_name: youtubeclonecontainer
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: youtubeclone:v1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    expose:
      - ${CONTAINER_PORT}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}